services:
  - type: web
    name: flask-messenger
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DB_HOST
        value: your-database-host
      - key: DB_USER
        value: your-db-user
      - key: DB_PASSWORD
        value: Omcf1318
      - key: DB_NAME
        value: login_py
